export const KEYBINDABLE_COMMANDS: ReadonlyArray<{ id: string; label: string }> = [
	{ id: 'open', label: 'Open file...' },
	{ id: 'save', label: 'Save file' },
	{ id: 'file.saveAll', label: 'Save all' },
	{ id: 'tabs.switch', label: 'Switch to...' },
	{ id: 'tabs.next', label: 'Next tab' },
	{ id: 'tabs.prev', label: 'Previous tab' },
	{ id: 'navigation.back', label: 'Go back' },
	{ id: 'navigation.forward', label: 'Go forward' },
	{ id: 'tabs.reopen', label: 'Reopen closed tab' },
	{ id: 'goto', label: 'Go to line...' },
	{ id: 'goto.definition', label: 'Go to definition' },
	{ id: 'find.file', label: 'In current file' },
	{ id: 'find.project', label: 'In project' },
	{ id: 'find.replaceProject', label: 'Replace in project' },
	{ id: 'file.new', label: 'New file' },
	{ id: 'open.cursor', label: 'Open file under cursor' },
	{ id: 'file.newDir', label: 'New folder' },
	{ id: 'file.copyPath', label: 'Copy path' },
	{ id: 'file.copyRelativePath', label: 'Copy relative path' },
	{ id: 'tabs.close', label: 'Close tab' },
	{ id: 'view.sidebar', label: 'Toggle sidebar' },
	{ id: 'view.preview', label: 'Preview file (no tab)' },
	{ id: 'view.sidebarPosition', label: 'Toggle sidebar position' },
	{ id: 'git.diffLayout', label: 'Toggle diff layout' },
	{ id: 'view.markdown', label: 'Markdown: rendered / source' },
	{ id: 'view.wrap', label: 'Toggle word wrap' },
	{ id: 'git.sourceControl', label: 'Source control panel' },
	{ id: 'view.extensions', label: 'Plugins panel' },
	{ id: 'view.review', label: 'Review panel' },
	{ id: 'problems.list', label: 'List problems' },
	{ id: 'problems.detail', label: 'Show problem at cursor' },
	{ id: 'problems.next', label: 'Next problem' },
	{ id: 'problems.prev', label: 'Previous problem' },
	{ id: 'problems.restart', label: 'Restart language servers' },
	{ id: 'review.note', label: 'Note this line for a review' },
	{ id: 'review.reply', label: 'Reply to the remark under the cursor' },
	{ id: 'editor.complete', label: 'Show completions' },
	{ id: 'editor.format', label: 'Format document' },
	{ id: 'editor.deleteLine', label: 'Delete line' },
	{ id: 'editor.lineStart', label: 'Go to beginning of line' },
	{ id: 'editor.fold', label: 'Fold block at cursor' },
	{ id: 'editor.unfold', label: 'Unfold block at cursor' },
	{ id: 'editor.foldAll', label: 'Fold everything' },
	{ id: 'editor.unfoldAll', label: 'Unfold everything' },
	{ id: 'editor.resolveConflict', label: 'Resolve conflict at cursor' },
	{ id: 'editor.nextConflict', label: 'Next conflict' },
	{ id: 'help', label: 'Keyboard shortcuts' },
	{ id: 'quit', label: 'Quit' },
];
